services:
  postgres:
    image: postgres:16-alpine
    container_name: steam_releases_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: steam_releases
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - steam_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: steam_releases_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - steam_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: steam_releases_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Database__ApplyMigrationsOnStartup=true
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=steam_releases;Username=postgres;Password=postgres;
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - steam_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  steam_network:
    driver: bridge