<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HttpClientFactory" Version="1.0.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamReleaseAnalytics.Core\SteamReleaseAnalytics.Core.csproj" />
    <ProjectReference Include="..\SteamReleaseAnalytics.Infrastructure\SteamReleaseAnalytics.Infrastructure.csproj" />
  </ItemGroup>

</Project>
